<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.waltz.tango</groupId>
        <artifactId>parent</artifactId>
        <version>1.5.1-SNAPSHOT</version>
        <relativePath>parent/pom.xml</relativePath>
    </parent>

    <artifactId>JTango-root</artifactId>

    <scm>
        <connection>scm:git:git@github.com:scientific-software-hub/JTango.git</connection>
        <developerConnection>scm:git:git@github.com:scientific-software-hub/JTango.git</developerConnection>
        <url>https://github.coms/cientific-software-hub/JTango</url>
        <tag>HEAD</tag>
    </scm>

    <modules>
        <module>parent</module>
        <module>common</module>
        <module>dao</module>
        <module>client</module>
        <module>server</module>
        <module>ez</module>
        <module>rx</module>
        <module>utils</module>
        <module>coverage-aggregated-report</module>
    </modules>

    <properties>
        <sonar.coverage.jacoco.xmlReportPaths>
            ${maven.multiModuleProjectDirectory}/coverage-aggregated-report/target/site/jacoco-aggregate/jacoco.xml
        </sonar.coverage.jacoco.xmlReportPaths>
    </properties>

    <name>JTango</name>
    <description>JTango common build parameters</description>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <localCheckout>true</localCheckout>
                    <tagNameFormat>JTango-@{project.version}</tagNameFormat>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
